Adnistrador/Controllers/AdministradorController.cs
using ClosedXML.Excel;
using Entidad;
using Entidad_;
using Negocios;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Adnistrador.Controllers
{
    [Authorize]
    public class AdministradorController : Controller
    {
        // GET: Administrador

        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ListaRol()
        {
            List<Rol> oLista = new List<Rol>();
            oLista = new CN_Roles().ListarRol();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ListarUsuario()
        {
            List<Usuarios> oLista = new List<Usuarios>();
            oLista = new CN_Usuarios().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarUsuario(Usuarios objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.id == 0)
            {
                resultado = new CN_Usuarios().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }


        [HttpGet]
        public JsonResult ListarReporte()
        {
            Dashboard oLista = new CN_Dashboard().Listar();
            return Json(new { resultado = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ListarReporteVenta(string fechainicio, string fechafin, string transaccion)
        {
            List<Reporte> oLista = new List<Reporte>();
            oLista = new CN_Dashboard().ListarReporte(fechainicio, fechafin, transaccion);
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public FileResult ExportarVenta(string fechainicio, string fechafin, string transaccion)
        {
            List<Reporte> oLista = new List<Reporte>();
            oLista = new CN_Dashboard().ListarReporte( fechainicio,  fechafin,  transaccion);
            DataTable dt = new DataTable();

            dt.Locale = new System.Globalization.CultureInfo("es-PE");
            dt.Columns.Add("Fecha Venta", typeof(string));
            dt.Columns.Add("Cliente", typeof(string));
            dt.Columns.Add("Producto", typeof(string));
            dt.Columns.Add("Precio", typeof(decimal));
            dt.Columns.Add("Cantidad", typeof(int));
            dt.Columns.Add("Total", typeof(decimal));
            dt.Columns.Add("IdTransaccion", typeof(string));

            foreach(Reporte rp in oLista)
            {
                dt.Rows.Add(new object[]
                {
                    rp.FechaVenta,
                    rp.Cliente,
                    rp.Producto,
                    rp.Precio,
                    rp.Cantidad,
                    rp.Total,
                    rp.IdTransaccion
                });
            }

            dt.TableName = "Datos";

            using(XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using(MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReporteVenta" + DateTime.Now.ToString() + ".xlsx");
                }
            }



        }



    }
}

Adnistrador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    <link rel="shortcut icon" href="/imagenes/logo.jpg" type="image/x-">
    <style>
        .sb-sidenav-menu-heading {
            font-family: 'Congenial Black', sans-serif;
            font-size: 20px;
            font-weight: bold;
            color: black; /* Color del texto, si es diferente del color predeterminado. */
        }

        .nav-link {
            display: block;
            padding: var(--bs-nav-link-padding-y) var(--bs-nav-link-padding-x);
            font-size: var(--bs-nav-link-font-size);
            font-weight: var(--bs-nav-link-font-weight);
            color: var(--bs-nav-link-color);
            text-decoration: none;
            transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out;
        }

            .nav-link:hover,
            .nav-link:focus {
                text-decoration: underline; /* Añadir una línea debajo del texto al pasar el cursor o enfocar el enlace */
                color: var(--bs-nav-link-hover-color); /* Cambiar el color al pasar el cursor o enfocar el enlace */
            }

        /* Estilo para el ícono */
        .sb-nav-link-icon {
            margin-right: 5px; /* Margen para separar el ícono del texto */
        }
    </style>
</head>
<body class="sb-nav-fixed ">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-success">
        <!-- Contenido de la barra de navegación aquí -->
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3 " href="">
            <img src="~/imagenes/logo.jpg" width="40" height="40" class="centered-image" />
        </a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!--<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo de Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion","Acceso")">Cerrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark bg-success" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @if (Session["IdRoles"].ToString() == "1")
                        {
                            <div class="sb-sidenav-menu-heading text-black" style="font-size: 20px;">Administrador</div>
                            <a class="nav-link text-white" href="@Url.Action("Dashboard","Administrador")">
                                <div class="sb-nav-link-icon text-white"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <a class="nav-link text-white" href="@Url.Action("Usuarios","Administrador")">
                                <div class="sb-nav-link-icon text-white"><i class="fas fa-users"></i></div>
                                Usuarios
                            </a>
                        }
                        <div class="sb-sidenav-menu-heading text-black" style="font-size: 20px;">Usuario</div>
                        <a class="nav-link text-white" href="@Url.Action("Categoria","Home")">
                            <div class="sb-nav-link-icon text-white"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link text-black text-white" href="@Url.Action("Marca","Home")">
                            <div class="sb-nav-link-icon text-white"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link text-white" href="@Url.Action("Producto","Home")">
                            <div class="sb-nav-link-icon text-white"><i class="fas fa-boxes"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4 ">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>
    @*

        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
    <script>
    function logoLinkClicked() {
        // Redirigir a la URL deseada
        if (Session["IdRoles"].ToString() == "1") {
            window.location.href = "@Url.Action("Dashboard", "Administrador")";
        } else {
            window.location.href = "@Url.Action("Categoria", "Home")";
        }
    }

    // Asociar la función al evento de clic del enlace.
    document.getElementById("logoLink").onclick = logoLinkClicked;
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>